//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsiGestionElementaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VParentEleve
    {
        public int IdEleve { get; set; }
        public int IdTuteur { get; set; }
        public string Matricule { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string NomTuteur { get; set; }
        public string PrenomTuteur { get; set; }
        public string CNI { get; set; }
    }
}
