//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsiGestionElementaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTuteur
    {
        public int IdEleve { get; set; }
        public int id { get; set; }
        public string NomTuteur { get; set; }
        public string PrenomTuteur { get; set; }
        public string AdresseTuteur { get; set; }
        public string TelTuteur { get; set; }
        public string EmailTuteur { get; set; }
        public string CiviliteTuteur { get; set; }
        public string Parente { get; set; }
        public string CNI { get; set; }
    }
}
